#!/bin/bash

# A pre-commit hook that makes it illegal to commit to develop
# on the repo.  An exception is made for 'arc', which is the preffered
# workflow.
#
# For emergencies, you can override this hook by using 'git commit -n'.

# 'arc' will set this ARCANIST environment variable while it runs a command
if [ -n "$ARCANIST" ]; then
    exit 0
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" = "develop" ]; then
    echo "FATAL ERROR: You cannot commit directly to the develop branch."
    echo
    echo "Commit to a feature branch instead."
    exit 1
fi
