#!/bin/sh

# A pre-push hook that makes it illegal to push to develop on the remote.  An
# exception is made for 'arc', which is the preffered workflow.
#
# For emergencies, you can override this hook by using 'git push --no-verify'.

# 'arc' will set this ARCANIST environment variable while it runs a command
if [ -n "$ARCANIST" ]; then
    exit 0
fi

# Each line has the format
#    <local ref> <sha> <remote ref> <sha>
# We complain if any remote ref is refs/heads/develop
while read local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_ref" = "refs/heads/develop" ]; then
        echo "FATAL ERROR: You cannot push to the develop branch on github."
        echo
        echo "Instead, you must deploy a feature branch via 'arc land'."
        exit 1
    fi
done
